version: '3.8'
services:
  business:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: business
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.business.rule=Host(`license.cards`) && PathPrefix(`/business`)"
      - "traefik.http.routers.business.middlewares=business-stripprefix"
      - "traefik.http.middlewares.business-stripprefix.stripprefix.prefixes=/business"
      - "traefik.http.routers.business.tls=true"
      - "traefik.http.routers.business.tls.certresolver=resolver"
    expose:  # new
      - 8000
networks:
  default:
    external:
      name: external-example