version: '3.8'
services:
  business:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: business
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`license.cards`) && PathPrefix(`/business`)"
      - "traefik.http.routers.web.middlewares=web-stripprefix"
      - "traefik.http.middlewares.web-stripprefix.stripprefix.prefixes=/business"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=resolver"
    expose:  # new
      - 8001
networks:
  default:
    external:
      name: external-example
