# Generated by Django 4.0.4 on 2022-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblusers',
            options={'managed': False, 'ordering': ['-userid']},
        ),
        migrations.AddField(
            model_name='token',
            name='companyId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
